### ISSUE TITLE
dev version chokes on importKey

### ISSUE THREAD

**Issue by working-name** [airmessage/airmessage-web#33]
Hello there,

Anything other than `localhost` seems to choke your app dead. How does one work with this? 

```
secureStorageUtils.ts:8 Uncaught TypeError: Cannot read properties of undefined (reading 'importKey')
```

I passed it `--host i.msg` and mapped `i.msg` to an intranet IP - the mac hosting the server as well.

Also, why only google sign in?

**Comment by tagavari** [comment]
I'm assuming this error is from [`crypto.subtle.importKey`](https://github.com/airmessage/airmessage-web/blob/765864beb604b0f334748e774ceaae48b893fb79/src/util/secureStorageUtils.ts#L10). If you're serving the page over HTTP, then the Web Crypto API is not available.

Google sign-in is the only option because it's a login provider that almost everyone is signed up with, and has support for contacts. If you're looking to run AirMessage on PC with a direct connection, the Android app is receiving updates to be a replacement to the web app.
